# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
common: &common
  adapter: postgresql
  password: password

development:
  <<: *common
  database: venue_development

test:
  <<: *common
  database: venue_test

production:
  <<: *common
  database: venue_production

