common: &common
  host: localhost
  adapter: postgresql
  password: password

development:
  <<: *common
  database: venue_development

test:
  <<: *common
  database: venue_test

production:
  <<: *common
  database: venue_production

